GarryClicker = GarryClicker or {}
GarryClicker.Notify = function(Text)
	return chat.AddText(Color(0, 255, 255), "[GARRYCLICKER] ", GarryClicker.DefaultColor or Color(0, 127, 255), Text)
end
local function a(b)
    return chat.AddText(Color(255, 127, 0), b)
end

GarryClicker.Notify("Downloading stats module...")
http.Fetch("https://raw.githubusercontent.com/Etothepowerof26/random/master/garryclicker/modules/stats.lua", function(content)
    RunString(content, "statsmodule", false)
    a("Stats module is done loading!")
end)
http.Fetch("https://raw.githubusercontent.com/Etothepowerof26/random/master/garryclicker/modules/ascensions.lua", function(content)
    RunString(content, "ascensionsmodule", false)
    a("Ascension module is done loading!")
end)
http.Fetch("https://raw.githubusercontent.com/Etothepowerof26/random/master/garryclicker/modules/data.lua", function(content)
    RunString(content, "datamodule", false)
    a("Data module is done loading!")
end)
http.Fetch("https://raw.githubusercontent.com/Etothepowerof26/random/master/garryclicker/modules/upgrades.lua", function(content)
    RunString(content, "upgradesmodule", false)
    a("Upgrades module is done loading!")
end)
http.Fetch("https://raw.githubusercontent.com/Etothepowerof26/random/master/garryclicker/modules/main.lua", function(content)
    RunString(content, "mainmodule", false)
    a("Main module is done loading!")
end)
timer.Simple(1, function()
	http.Fetch("https://raw.githubusercontent.com/Etothepowerof26/random/master/garryclicker/modules/init.lua", function(content)
		GarryClicker.Notify("Initiating GarryClicker...")
		RunString(content, "initmodule", false)
	end)
end)
